<script lang="ts">
	export let data;

	$: alreadySet = !!data.bitcoinNodeless.publicKey;
</script>

<h1 class="text-3xl">Bitcoin nodeless</h1>

<p>
	Enter your public key. Bebop will be able to generate new addresses and check funds received, but
	you have full control of the funds on your own wallet.
</p>

<h2 class="text-2xl">Configuration</h2>

<form method="post" class="flex flex-col gap-4">
	<label class="form-label">
		BIP standard
		<input type="text" readonly value="BIP 84" class="form-input" />
		<p class="text-sm">
			BIP 84 is the only supported format at the moment. We may add support for BIP 86 later on.
		</p>
	</label>

	<label class="form-label">
		Public key (ZPub)
		<input
			type="text"
			name="publicKey"
			class="form-input"
			required
			placeholder="zpub..."
			readonly={alreadySet}
			value={data.bitcoinNodeless.publicKey}
		/>
		<p class="text-sm">
			A BIP84 zpub key (or vpub for testnet). You can use a wallet such as <a
				href="https://sparrowwallet.com/"
				rel="noreferrer">Sparrow Wallet</a
			> to generate one. The derivation path should be m/84'/0'/0' for mainnet and m/84'/1'/0' for testnet.
		</p>
	</label>

	<label class="form-label">
		Derivation index

		<input
			type="number"
			name="derivationIndex"
			class="form-input"
			required
			disabled={alreadySet}
			value={data.bitcoinNodeless.derivationIndex}
		/>

		<p class="text-sm">
			The derivation index is the index of the address to generate. It starts at 0 and increments by
			1 for each new address / bitcoin payment request on bebop. DO NOT CHANGE THIS VALUE unless you
			know what you are doing. It can lead to reusing existing addresses or creating addresses not
			detected by your wallet.
		</p>
	</label>

	<label class="form-label">
		Mempool URL
		<input
			type="url"
			name="mempoolUrl"
			class="form-input"
			value={data.bitcoinNodeless.mempoolUrl}
			required
		/>
		<p class="text-sm">
			The URL of the mempool API to use, to check incoming funds on the generated addresses. You can
			add a /testnet suffix. The official API is rate-limited, but you can host your own as the
			project is <a href="https://github.com/mempool/mempool" rel="noreferrer">open-source</a>.
		</p>
	</label>

	<div class="flex gap-2">
		{#if alreadySet}
			<button class="btn btn-black" type="submit" formaction="?/update">Update</button>
			<button
				class="btn btn-red ml-auto"
				type="submit"
				formaction="?/delete"
				on:click={(e) =>
					confirm('Delete bitcoin nodeless configuration? This action cannot be undone.')
						? true
						: e.preventDefault()}>Delete configuration</button
			>
		{:else}
			<button class="btn btn-black" type="submit" formaction="?/initialize">Set up</button>
		{/if}
	</div>
</form>

{#if data.nextAddresses.length}
	<h2 class="text-2xl">Next addresses</h2>

	<p>Those will be the next addresses generated by bebop</p>

	<ul class="font-mono">
		{#each data.nextAddresses as address}
			<li class="font-mono">- {address}</li>
		{/each}
	</ul>
{/if}
