name: deploy-bootik2

on:
  workflow_dispatch:

jobs:
  deploy-bootik2:
    runs-on: ubuntu-latest
    environment:
      name: bootik2
      url: ${{ vars.DEPLOY_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.3.1
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'pnpm'
      - run: |
          pnpm install --frozen-lockfile
          echo $DOT_ENV > .env.local
          pnpm build
        env:
          DOT_ENV: ${{ vars.DOT_ENV }}
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # ssh-keygen -H -F [<host>]:<port>
          known_hosts: ${{ vars.SSH_KNOWN_HOSTS }}
      - name: Deploy
        run: |
          zip -r build.zip build
          scp -P ${{ vars.SSH_PORT }} -r build.zip ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }}:B2BitcoinBootik2/build.zip
          ssh -p ${{ vars.SSH_PORT }} ${{ vars.SSH_USER }}@${{ vars.SSH_HOST }} "hostnamectl && git lfs install && cd B2BitcoinBootik2 && git remote prune origin && git fetch && git checkout $GITHUB_SHA && pnpm install && unzip -o build.zip && pm2 reload bootik2"
