name: Lint
on:
  pull_request:
  # push:
  #   branches:
  #     - main

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          diff_relative: true
          files: |
            **/*.ts
            **/*.svelte
      - uses: pnpm/action-setup@v2
        with:
          version: 8.3.1
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'
      - run: |
          pnpm install --frozen-lockfile
      # Run this first to generate .svelte-kit/tsconfig.json
      - name: 'Build'
        run: |
          pnpm run build
      - name: 'Checking prettier errors'
        run: |
          if [ -z "${{ steps.changed-files.outputs.all_changed_files }}" ]
          then
            echo "no changed files to test"
          else
            pnpm run format ${{ steps.changed-files.outputs.all_changed_files }};
            git diff | head -n 100;
            git diff --name-only --exit-code
          fi
      - name: 'Checking lint errors'
        run: |
          if [ -z "${{ steps.changed-files.outputs.all_changed_files }}" ]
          then
            echo "no changed files to test"
          else
            pnpm run lint ${{ steps.changed-files.outputs.all_changed_files }};
            git diff | head -n 100;
            git diff --name-only --exit-code
          fi
      - name: 'Checking type errors'
        run: |
          pnpm run check
